name: "CLEAN UP"
description: exclui branches fora do padrao
title: "[clean] branches"
labels: ["clean"]

body:
  - type: markdown
    attributes:
      value: |
        Deleção de branches antigas

  - type: textarea
    id: branches
    attributes:
      label: "Motivo da limpeza"
      description: "descreva o motivo da limpeza"
      placeholder: |
        repositorio acumulou mais de x branches

    validations:
      required: true