name: shell-action
author: Wanderlucio P Silva
description: this action is for testing my shell scripts as gh actions
  
runs:
  using: 'composite'
  steps:
  - run: entrypoint.sh
    shell: bash
    env:
      PR: ${{ github.event.pull_request._links.html.href }}
      GH_TOKEN: ${{ github.token }}