name: CLEAN
on:
  issues:
    types: [opened]
jobs:
  execute:
    # if: github.event.issue.title == '[clean] branches'
    if: contains(github.event.issue.title, '[clean]')
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: read issue
        run: |
          echo "numero da issue: ${{ github.event.issue.number }}"
          echo "titulo da issue: ${{ github.event.issue.title }}"
          echo "body da issue: ${{ github.event.issue.body }}"
      
      - name: show event infos
        run: echo '${{ toJSON(github) }}'

      - name: close issue
        shell: bash
        run: |
          echo "closing issue..."
          gh issue close -R "$(( github.event.repository ))" \
          --reason "solved!" \
          --comment "solved!" \
          "${{ github.event.issue.number }}"
          echo "issue successful closed!"
        env:
          GH_TOKEN: ${{ github.token }}

          