name: clean
on:
  issues:
    types: opened
jobs:
  execute:
    # if: github.event.issue.title == '[clean] branches'
    if: contains(github.event.issue.title, '[clean]')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3     
      - name: show event infos
        run: echo '${{ toJSON(github) }}'
      - name: process
        shell: bash
        run: |
          echo "repository: ${{ github.repository }}"
          echo "issue's number: ${{ github.event.issue.number }}"
          echo "issue's title: ${{ github.event.issue.title }}"
          echo "issue's body: ${{ github.event.issue.body }}"   
          echo "----------------------------------------------------------"
          echo "here I can call an action to clean up branches"
          echo "----------------------------------------------------------"
          echo "closing issue..."
          gh issue close -R "${{ github.repository }}" \
          --reason "completed" \
          --comment "solved!" \
          "${{ github.event.issue.number }}"
          echo "issue successful closed!"
          echo "----------------------------------------------------------"
        env:
          GH_TOKEN: ${{ github.token }}          