name: pygh
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: ls -la
      - name: get merged branches
        id: branches
        run: |
          echo teste=$(git branch --merged main)
          echo $teste
        shell: bash
      - name: execute
        uses: ./.github/actions/pygh
        with:
          tk: ${{ secrets.TOKEN }}
          branches: ${{ steps.branches.outputs.teste }}