name: pygh
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - run: ls -la
      - name: install terraform cli
        uses: hashicorp/setup-terraform@v2.0.3
      - name: execute
        uses: ./.github/actions/pygh
        with:
          tk: ${{ secrets.TOKEN }}